--vim.keymap.set('n', '<leader>y', '"*yy')
--vim.keymap.set('v', '<leader>y', '"*y')
--vim.keymap.set('n', '<leader>p', '"*p')

vim.keymap.set("n", "<space><space>x", "<cmd>source %<CR>")
vim.keymap.set("n", "<space>x", ":.lua<CR>")
vim.keymap.set("v", "<space>x", ":lua<CR>")

vim.keymap.set('n', '<leader>.', '<c-^>')
vim.keymap.set('n', 'H', '^')
vim.keymap.set('n', 'L', '$')
vim.keymap.set('n', 'U', 'mmviw~`m')
vim.keymap.set('n', '<leader>r', ':!%:p<cr>')
vim.keymap.set('n', '<leader>h', ':set hls!<cr>')
vim.keymap.set('n', '<leader>w', ':set wrap!<cr>')
vim.keymap.set('n', '<leader>d', ':bp<bar>vs<bar>bn<bar>bd<cr>')
